#!/usr/bin/env bash
set -euo pipefail

cd '/Users/tyronewhite/masters_research_code/blimp-rare'
mkdir -p '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/acceptability_pair_scores_pythia' '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/manifests/pythia_behavior_gate'

echo '[Run] EleutherAI/pythia-1.4b head'
python3 '/Users/tyronewhite/masters_research_code/blimp-rare/scripts/score_acceptability_methods.py' --data '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/causative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/inchoative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/transitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/intransitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/drop_argument.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/passive_1.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/passive_2.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/principle_A_domain_3.jsonl' --models 'EleutherAI/pythia-1.4b' --methods lp_readout in_template_lp --variant freq --batch-size 16 --max-length 256 --device 'cuda' --dtype 'bfloat16' --out-dir '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/acceptability_pair_scores_pythia' --run-timestamp '20260617-pythia-gate-head' --manifest-out '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/manifests/pythia_behavior_gate/20260617-pythia-gate-head-pythia-1_4b.json'

echo '[Run] EleutherAI/pythia-1.4b tail'
python3 '/Users/tyronewhite/masters_research_code/blimp-rare/scripts/score_acceptability_methods.py' --data '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/causative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/inchoative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/transitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/intransitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/drop_argument.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/passive_1.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/passive_2.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/principle_A_domain_3.jsonl' --models 'EleutherAI/pythia-1.4b' --methods lp_readout in_template_lp --variant freq --batch-size 16 --max-length 256 --device 'cuda' --dtype 'bfloat16' --out-dir '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/acceptability_pair_scores_pythia' --run-timestamp '20260617-pythia-gate-tail' --manifest-out '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/manifests/pythia_behavior_gate/20260617-pythia-gate-tail-pythia-1_4b.json'

echo '[Run] EleutherAI/pythia-1.4b xtail'
python3 '/Users/tyronewhite/masters_research_code/blimp-rare/scripts/score_acceptability_methods.py' --data '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/causative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/inchoative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/transitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/intransitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/drop_argument.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/passive_1.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/passive_2.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/principle_A_domain_3.jsonl' --models 'EleutherAI/pythia-1.4b' --methods lp_readout in_template_lp --variant freq --batch-size 16 --max-length 256 --device 'cuda' --dtype 'bfloat16' --out-dir '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/acceptability_pair_scores_pythia' --run-timestamp '20260617-pythia-gate-xtail' --manifest-out '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/manifests/pythia_behavior_gate/20260617-pythia-gate-xtail-pythia-1_4b.json'

echo '[Run] EleutherAI/pythia-2.8b head'
python3 '/Users/tyronewhite/masters_research_code/blimp-rare/scripts/score_acceptability_methods.py' --data '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/causative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/inchoative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/transitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/intransitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/drop_argument.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/passive_1.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/passive_2.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/principle_A_domain_3.jsonl' --models 'EleutherAI/pythia-2.8b' --methods lp_readout in_template_lp --variant freq --batch-size 16 --max-length 256 --device 'cuda' --dtype 'bfloat16' --out-dir '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/acceptability_pair_scores_pythia' --run-timestamp '20260617-pythia-gate-head' --manifest-out '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/manifests/pythia_behavior_gate/20260617-pythia-gate-head-pythia-2_8b.json'

echo '[Run] EleutherAI/pythia-2.8b tail'
python3 '/Users/tyronewhite/masters_research_code/blimp-rare/scripts/score_acceptability_methods.py' --data '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/causative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/inchoative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/transitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/intransitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/drop_argument.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/passive_1.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/passive_2.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/principle_A_domain_3.jsonl' --models 'EleutherAI/pythia-2.8b' --methods lp_readout in_template_lp --variant freq --batch-size 16 --max-length 256 --device 'cuda' --dtype 'bfloat16' --out-dir '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/acceptability_pair_scores_pythia' --run-timestamp '20260617-pythia-gate-tail' --manifest-out '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/manifests/pythia_behavior_gate/20260617-pythia-gate-tail-pythia-2_8b.json'

echo '[Run] EleutherAI/pythia-2.8b xtail'
python3 '/Users/tyronewhite/masters_research_code/blimp-rare/scripts/score_acceptability_methods.py' --data '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/causative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/inchoative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/transitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/intransitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/drop_argument.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/passive_1.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/passive_2.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/principle_A_domain_3.jsonl' --models 'EleutherAI/pythia-2.8b' --methods lp_readout in_template_lp --variant freq --batch-size 16 --max-length 256 --device 'cuda' --dtype 'bfloat16' --out-dir '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/acceptability_pair_scores_pythia' --run-timestamp '20260617-pythia-gate-xtail' --manifest-out '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/manifests/pythia_behavior_gate/20260617-pythia-gate-xtail-pythia-2_8b.json'

echo '[Run] EleutherAI/pythia-6.9b head'
python3 '/Users/tyronewhite/masters_research_code/blimp-rare/scripts/score_acceptability_methods.py' --data '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/causative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/inchoative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/transitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/intransitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/drop_argument.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/passive_1.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/passive_2.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/head/principle_A_domain_3.jsonl' --models 'EleutherAI/pythia-6.9b' --methods lp_readout in_template_lp --variant freq --batch-size 16 --max-length 256 --device 'cuda' --dtype 'bfloat16' --out-dir '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/acceptability_pair_scores_pythia' --run-timestamp '20260617-pythia-gate-head' --manifest-out '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/manifests/pythia_behavior_gate/20260617-pythia-gate-head-pythia-6_9b.json'

echo '[Run] EleutherAI/pythia-6.9b tail'
python3 '/Users/tyronewhite/masters_research_code/blimp-rare/scripts/score_acceptability_methods.py' --data '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/causative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/inchoative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/transitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/intransitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/drop_argument.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/passive_1.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/passive_2.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/tail/principle_A_domain_3.jsonl' --models 'EleutherAI/pythia-6.9b' --methods lp_readout in_template_lp --variant freq --batch-size 16 --max-length 256 --device 'cuda' --dtype 'bfloat16' --out-dir '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/acceptability_pair_scores_pythia' --run-timestamp '20260617-pythia-gate-tail' --manifest-out '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/manifests/pythia_behavior_gate/20260617-pythia-gate-tail-pythia-6_9b.json'

echo '[Run] EleutherAI/pythia-6.9b xtail'
python3 '/Users/tyronewhite/masters_research_code/blimp-rare/scripts/score_acceptability_methods.py' --data '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/causative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/inchoative.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/transitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/intransitive.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/drop_argument.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/passive_1.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/passive_2.jsonl' '/Users/tyronewhite/masters_research_code/freq-blimp/data/freqblimp/xtail/principle_A_domain_3.jsonl' --models 'EleutherAI/pythia-6.9b' --methods lp_readout in_template_lp --variant freq --batch-size 16 --max-length 256 --device 'cuda' --dtype 'bfloat16' --out-dir '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/acceptability_pair_scores_pythia' --run-timestamp '20260617-pythia-gate-xtail' --manifest-out '/Users/tyronewhite/masters_research_code/lexical_licensing_interp/results/manifests/pythia_behavior_gate/20260617-pythia-gate-xtail-pythia-6_9b.json'

